export const ACTIONS = {
    LOAD_POKEMONS: 'LOAD_POKEMONS',
    FILTER_POKEMONS: 'FILTER_POKEMONS',
    UPDATE_POKEMON: 'UPDATE_POKEMON',
    SET_PER_PAGE: 'SET_PER_PAGE',
    SEARCH_NEXT_PAGE: 'SEARCH_NEXT_PAGE',
    SEARCH_PREV_PAGE: 'SEARCH_PREV_PAGE'
};